// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateStatesInput struct {
	Time    string `json:"time"`
	Machine string `json:"machine"`
	Name    string `json:"name"`
	Color   string `json:"color"`
	Value   int    `json:"value"`
}

type Identifier struct {
	Name  string  `json:"name"`
	Value float64 `json:"value"`
}

type IdentifierFilterInput struct {
	Identifier *StringQueryOperatorInput `json:"identifier,omitempty"`
}

type Mutation struct {
}

type Plc struct {
	Time       string        `json:"time"`
	Machine    string        `json:"machine"`
	Identifier []*Identifier `json:"identifier"`
}

type Query struct {
}

type State struct {
	Time    string `json:"time"`
	Machine string `json:"machine"`
	Name    string `json:"name"`
	Color   string `json:"color"`
	Value   int    `json:"value"`
}

type StringQueryOperatorInput struct {
	Eq    *string   `json:"eq,omitempty"`
	Ne    *string   `json:"ne,omitempty"`
	In    []*string `json:"in,omitempty"`
	Nin   []*string `json:"nin,omitempty"`
	Regex *string   `json:"regex,omitempty"`
	Glob  *string   `json:"glob,omitempty"`
}
