version: '3'

name: microservice-architecture

services:
  graphql-machine-service:
    container_name: graphql-api
    build:
      context: ./../graphql-machine-service
      dockerfile: ./../graphql-machine-service/graphql-machine-service.dockerfile
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1


  grpc-logger-service:
    container_name: grpc-api
    build:
      context: ./../grpc-logger-service
      dockerfile: ./../grpc-logger-service/grpc-logger-service.dockerfile
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1 

    
  restful-broker-service:
    container_name: restful-api
    build:
      context: ./../restful-broker-service
      dockerfile: ./../restful-broker-service/restful-broker-service.dockerfile
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1 


  statemachine-service:
    container_name: statemachine-service
    build:
      context: ./../statemachine-service
      dockerfile: ./../statemachine-service/statemachine-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1 

